schema:
  - ${NEXT_PUBLIC_GRAPHQL_ENDPOINT}
  - '**/*.graphqls'
  - '../../packages/**/*.graphqls'
  #- '.packages/mollie-magento-payment/**/*.graphqls'
documents:
  - 'components/**/*.graphql'
  - '../../packages/**/*.graphql'
plugins:
  - '@graphcommerce/graphql-codegen-relay-optimizer-plugin'
  - typed-document-node
  - typescript-operations
  - add
preset: '@graphcommerce/graphql-codegen-near-operation-file'
presetConfig:
  extension: .gql.ts
  baseTypesPath: ~@graphcommerce/graphql
  injectables: true
config:
  skipTypename: true
  dedupeOperationSuffix: true
  content: '/* eslint-disable */'
cacheDir: .cache/graphql-let/examples/magento-graphql
respectGitIgnore: false
